### ISSUE TITLE
Unable to run CUDA mode after Summit RHEL 8 upgrade

### ISSUE THREAD

**Issue by MalachiTimothyPhillips** [Nek5000/nekRS#369] opened 2021-08-19 22:52 UTC
**Describe the bug**
After the Summit RHEL 8 upgrade, occa has been unable to run CUDA mode in both the `master` and `next` branches.

**To Reproduce**
`ssh <username>@summit.olcf.ornl.gov`
1. `ssh <username>@summit.olcf.ornl.gov`
2. `module load gcc cmake cuda`
3. Build, e.g. `./makenrs` for `master`, or `./nrsconfig && cmake --build ./build --target install -j8` for `next`
3. Run, e.g., `echo "Y" | ./nrsqsub_summit ethier 1 00:05`

Pre-compilation output:
```
                 __    ____  _____
   ____   ___   / /__ / __ \/ ___/
  / __ \ / _ \ / //_// /_/ /\__ \ 
 / / / //  __// ,<  / _, _/___/ / 
/_/ /_/ \___//_/|_|/_/ |_|/____/  v21.1 (ffc02bca)

COPYRIGHT (c) 2019-2021 UCHICAGO ARGONNE, LLC

MPI tasks: 1

using NEKRS_HOME: /ccs/home/malachi/.local/nekrs
using OCCA_CACHE_DIR: /gpfs/alpine/csc262/scratch/malachi/ethier/.cache/occa/

Initializing device 
[CUDA] mode is not enabled, defaulting to [Serial] mode
active occa mode: Serial

active occa mode does not match selected backend!
```

**Comment by yslan** [comment] 2021-08-20 00:07
A easier way to reproduce:
`cd nekrs/3rd_party/occa`
`make -j`
Then it will show occa info and CUDA is not there as a backend.

**Comment by stgeke** [comment] 2021-08-21 06:05
Looks like this was fixed by OLCF.

**Closed by stgeke** 2021-08-21 06:05 UTC
Labels: bug, PRIO

**Comment by nandini1610** [comment] 2022-06-17 21:35
I have the similar issue let me know the fix please?
