### ISSUE TITLE
Add error checking on user misspellings in .par

### ISSUE THREAD

**Issue by aprilnovak** [Nek5000/nekRS#169] opened 2020-11-13 15:31 UTC
In the `.par` file, if a user misspells `boundaryTypeMap` as `boundaryTypeMape`, for instance (like I just did), there should be an error telling them that there were unused parameters in their input file. Otherwise this can be very difficult to debug.

**Comment by stgeke** [comment] 2020-11-13 15:32
Duplicate of #2

**Closed by stgeke** 2020-11-13 15:32 UTC

**Comment by aprilnovak** [comment] 2020-11-13 15:34
my mistake!
